spring.application.name=absensikerja
# DATABASE
spring.datasource.url=jdbc:postgresql://localhost/absensikerja
spring.datasource.username=postgres
spring.datasource.password=gajah

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=10

server.port=8192
server.servlet.context-path=/absensikerja

app.base-url=http://localhost:8192/absensikerja
app.frontend-url=http://localhost:4300/ak


security.jwt.secret-key=11540bbc355a496f48c5702fb07a7f3d79c65451bc4c629d1dfa06534981a126
security.jwt.expiration-time-hour=24

# ?? Email (SMTP) ??????????????????????????????????????????????????????????????
spring.mail.host=smtp.mail.yahoo.com
spring.mail.port=587
spring.mail.username=luaindonesia@yahoo.com
spring.mail.password=vdsqxwrcpddcqsak
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.mail.yahoo.com
spring.mail.properties.from=luaindonesia@yahoo.com
app.mail.from=AbsensiKerja <luaindonesia@yahoo.com>
